services:
  server:
    environment:
      NODE_ENV: production
    env_file:
      - ./server/.env.production

    command: npm run start:prod

  client:
    environment:
      NODE_ENV: production
    command: npm run start
